#!/usr/bin/env bash
# generate-config.sh — Probe a project directory and generate a starter horus.config.json.
#
# Usage:
#   ./scripts/generate-config.sh                  # probe current directory
#   ./scripts/generate-config.sh <project-dir>    # probe a specific directory
#   ./scripts/generate-config.sh <dir> --output <file>  # write to file instead of stdout
#
# The generated config can be passed to install-local.sh:
#   ./scripts/generate-config.sh myproject --output myproject/horus.config.json
#   ./scripts/install-local.sh myproject/horus

set -eu

root="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
scan_dir="$(pwd)"
output_file=""

while [ $# -gt 0 ]; do
  case "$1" in
    --output)   shift; output_file="${1:-}" ;;
    --output=*) output_file="${1#--output=}" ;;
    -h|--help)
      printf 'Usage: %s [project-dir] [--output file]\n' "$0"; exit 0 ;;
    -*)
      printf 'Unknown option: %s\n' "$1" >&2; exit 2 ;;
    *)
      scan_dir="$1" ;;
  esac
  shift
done

[ -d "$scan_dir" ] || { printf 'Directory not found: %s\n' "$scan_dir" >&2; exit 2; }

# ── extension detection ───────────────────────────────────────────────────────

has_ext() {
  find "$scan_dir" -maxdepth 6 \( -name "*.$1" \) \
    -not -path '*/.git/*' \
    -not -path '*/node_modules/*' \
    -not -path '*/vendor/*' \
    -not -path '*/.venv/*' \
    | head -1 | grep -q . 2>/dev/null
}

langs=""
agents=""
skills=""

# Language detection and agent/skill mapping
detect() {
  local ext="$1" lang="$2" lang_agents="$3" lang_skills="$4"
  if has_ext "$ext"; then
    langs="$langs \"$lang\","
    agents="$agents $lang_agents,"
    skills="$skills $lang_skills,"
  fi
}

# Common always included
langs='"common",'
agents='"code-reviewer", "security-reviewer", "architect", "planner",'
skills='"code-review", "security-review", "plan-feature", "git-review",'

detect "ts"    "typescript"    '"typescript-reviewer"'    '"tdd", "verification-loop"'
detect "tsx"   "typescript"    ''                         ''
detect "py"    "python"        '"python-reviewer"'        '"python-patterns", "python-testing"'
detect "go"    "golang"        '"go-reviewer"'            '"golang-patterns", "golang-testing"'
detect "java"  "java"          '"java-reviewer", "java-build-resolver"'   '"java-coding-standards"'
detect "kt"    "kotlin"        '"kotlin-reviewer", "kotlin-build-resolver"' ''
detect "rs"    "rust"          '"rust-reviewer", "rust-build-resolver"'   ''
detect "cpp"   "cpp"           '"cpp-reviewer", "cpp-build-resolver"'     '"cpp-coding-standards"'
detect "cs"    "csharp"        '"csharp-reviewer"'        ''
detect "swift" "swift"         ''                         '"swift-actor-persistence"'
detect "php"   "php"           ''                         '"laravel-patterns"'
detect "pl"    "perl"          ''                         '"perl-patterns"'
detect "sql"   "database"      '"database-reviewer"'      '"database-migrations"'
detect "html"  "web"           '"a11y-architect"'         '"frontend-patterns"'
detect "css"   "web"           ''                         ''
detect "jsx"   "web"           ''                         ''

# Check for test files → add tdd-guide
if has_ext "test.ts" || has_ext "spec.ts" || has_ext "test.py" || \
   find "$scan_dir" -maxdepth 6 -name "*.test.*" -not -path '*/.git/*' | head -1 | grep -q . 2>/dev/null; then
  agents="$agents \"tdd-guide\","
  skills="$skills \"tdd\", \"e2e-testing\","
fi

# Deduplicate and clean up
clean_list() {
  printf '%s\n' "$1" | tr ',' '\n' | grep -v '^[[:space:]]*$' | sort -u | \
    grep -v '^$' | sed 's/^[[:space:]]*/    /' | paste -sd ',' - | \
    sed 's/,/, /g' | sed 's/^[[:space:]]*//' || true
}

langs_clean="$(printf '%s\n' "$langs" | tr ',' '\n' | grep -v '^[[:space:]]*$' | sort -u | \
  grep -v '^$' | sed 's/^[[:space:]]*//' | grep -v '^$' | \
  awk '{printf "    %s,\n", $0}' | sed '$ s/,$//')"

agents_clean="$(printf '%s\n' "$agents" | tr ',' '\n' | grep -v '^[[:space:]]*$' | sort -u | \
  grep -v '^$' | sed 's/^[[:space:]]*//' | grep -v '^"$' | grep '"' | \
  awk '{printf "    %s,\n", $0}' | sed '$ s/,$//')"

skills_clean="$(printf '%s\n' "$skills" | tr ',' '\n' | grep -v '^[[:space:]]*$' | sort -u | \
  grep -v '^$' | sed 's/^[[:space:]]*//' | grep -v '^"$' | grep '"' | \
  awk '{printf "    %s,\n", $0}' | sed '$ s/,$//')"

# ── generate JSON ─────────────────────────────────────────────────────────────

config="$(cat <<EOF
{
  "_comment": "Agent Runtime Guard project config — generated by generate-config.sh for: $scan_dir",
  "_generated": "$(date +%Y-%m-%d)",

  "profile": "full",

  "languages": [
$langs_clean
  ],

  "agents": [
$agents_clean
  ],

  "skills": [
$skills_clean
  ],

  "extra_rules": [],

  "hooks": {
    "enforce_secrets": false
  },

  "runtime": {
    "trust_posture": "balanced",
    "protected_branches": ["main", "master"],
    "sensitive_path_patterns": ["prod", "production", "secrets", "credentials", ".env", "terraform", "infra"]
  }
}
EOF
)"

if [ -n "$output_file" ]; then
  printf '%s\n' "$config" > "$output_file"
  printf 'Config written to: %s\n' "$output_file"
  printf 'Next: ./scripts/install-local.sh <target-dir>\n'
else
  printf '%s\n' "$config"
fi
